apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-application
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: cloud-application
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
